name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.11'
          environment-file: Implementez_un_modele_de_scoring/conda.yaml
          auto-activate-base: false

      - name: Install build essentials
        run: sudo apt-get install -y build-essential python3-dev

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsnappy-dev

      - name: Install Cython
        run: |
          conda activate mlflow-env  
          pip install cython

      - name: Install Python dependencies
        run: |
          conda activate mlflow-env  
          pip install -r Implementez_un_modele_de_scoring/requirements.txt

      - name: Download files from S3
        run: |
          aws s3 cp s3://elasticbeanstalk-eu-north-1-182399693743/model.pkl model.pkl
          aws s3 cp s3://elasticbeanstalk-eu-north-1-182399693743/imputer.pkl imputer.pkl
          aws s3 cp s3://elasticbeanstalk-eu-north-1-182399693743/scaler.pkl scaler.pkl
          aws s3 cp s3://elasticbeanstalk-eu-north-1-182399693743/feature_names.json feature_names.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        working-directory: /home/runner/work/Implementez_un_modele_de_scoring/Implementez_un_modele_de_scoring

      - name: Deploy to Elastic Beanstalk
        run: eb deploy
        working-directory: /home/runner/work/Implementez_un_modele_de_scoring/Implementez_un_modele_de_scoring
