name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # DÃ©clenche le workflow sur des commits dans la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Print working directory
      run: pwd
    
    - name: List files
      run: ls -la ${{ github.workspace }}
    
    - name: Install dependencies
      run: |
        pip install -r ${{ github.workspace }}/requirements.txt
    
    - name: Install dependencies
      run: |
        cd /home/runner/work/Implementez_un_modele_de_scoring  # Navigate to the root directory
        pip install -r requirements.txt
    
    - name: Checkout code
      uses: actions/checkout@v3

    # Download the model from S3
    - name: Download model from S3
      run: |
        aws s3 cp s3://elasticbeanstalk-eu-north-1-182399693743/model.pkl MLmodel.pkl
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    # Packaging the model
    - name: Package model
      run: zip -r model-package.zip MLmodel.pkl

    # Upload model to S3 using AWS CLI
    - name: Upload model to S3
      run: |
        aws s3 cp model-package.zip s3://elasticbeanstalk-eu-north-1-182399693743/MLmodel/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    # Deploy the model to Elastic Beanstalk
    - name: Deploy to Elastic Beanstalk
      run: |
        VERSION_LABEL=$(date +%Y%m%d%H%M%S)
        aws elasticbeanstalk create-application-version --application-name Scoring-client-env --version-label $VERSION_LABEL --source-bundle S3Bucket=elasticbeanstalk-eu-north-1-182399693743,S3Key=MLmodel/model-package.zip --region eu-north-1
        aws elasticbeanstalk update-environment --environment-name Scoring-client-env-env --version-label $VERSION_LABEL --region eu-north-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
